name: tictactoe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  customprompt: ^0.2.6+9
  device_preview: ^0.7.1
  flutter_svg: ^0.22.0
  line_awesome_flutter: ^1.0.1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400

# flutter_icons:
#   ios: true
#   android: true
#   image_path_ios: "assets/launcher/icon.png"
#   image_path_android: "assets/launcher/icon.png"
#   adaptive_icon_background: "#343537"
#   adaptive_icon_foreground: assets/launcher/ic_foreground.png
